In [9]:
import numpy

print numpy.version.full_version

1.13.3


In [12]:
## 在import扩展模块时添加模块在程序中的别名

import numpy as np

print np.version.full_version

1.13.3


In [23]:
## NumPy中的基本对象是同类型的多维数组（homogeneous multidimensional array）

a = np.arange(12)

print a

##生成了一个一维数组a，从0开始，步长为1，长度为12

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
##查看变量类型
print type(a)

<type 'numpy.ndarray'>


In [24]:
##reshape重新构造数组,把长度为12的一维数组，构造成3*4的二维数组,3行4列的数组 

a = a.reshape(3, 4)

print a


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
#更高维的数组

a = a.reshape(3, 2, 2)

print a

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [35]:
'''
ndim查看维度

shape查看各维度的大小

size查看全部的元素个数，等于各维度大小的乘积

dtype可查看元素类型

itemsize查看元素占位（bytes）大小

'''

print a.ndim
print a.shape
print a.size
print a.dtype
print a.itemsize

3
(3, 2, 2)
12
int64
8


In [36]:
#创建数组,数组的创建可通过转换列表实现

raw = [0,1,2,3,4]
a = np.array(raw)

print a


[0 1 2 3 4]


In [37]:
#高维数组可通过转换嵌套列表实现

raw = [[0,1,2,3,4], [5,6,7,8,9]]

b = np.array(raw)

print b

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
#一些特殊的数组有特别定制的命令生成，如3*8的全零矩阵：

d = (3, 8)

z=np.zeros(d)

print z

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [41]:
#默认生成的类型是浮点型

print z.dtype

float64


In [43]:
#可以通过指定类型改为整型

d = (4, 5)

i=np.ones(d, dtype=int)

print i.dtype

int64


In [49]:
#加减乘除 + - * /,运算都是基于全部的数组元素的

a = np.array([[1.0, 2], [2, 4]])

print "a:"

print a

b = np.array([[3.2, 1.5], [2.5, 4]])

print "b:"

print b

print "a/b:"

print a/b

a:
[[ 1.  2.]
 [ 2.  4.]]
b:
[[ 3.2  1.5]
 [ 2.5  4. ]]
a/b:
[[ 0.3125      1.33333333]
 [ 0.8         1.        ]]


In [51]:
# 运算符也可以对标量和数组操作，结果是数组的全部元素对这个标量进行运算，还是一个数组

print "2 * a:"

print 2 * a

print "b - 1.2:"

print b - 1.2


2 * a:
[[ 2.  4.]
 [ 4.  8.]]
b - 1.2:
[[ 2.   0.3]
 [ 1.3  2.8]]


In [54]:
# +=  -=  *=  /= 操作符在NumPy中同样支持

a*=2

print a

[[  6.   8.]
 [  8.  12.]]


In [60]:
# 最大 最小值,全部元素的和、按行求和、按列求和

a = np.arange(20).reshape(4,5)

print "a:"

print a

print "sum of all elements in a: " + str(a.sum())

print "maximum element in a: " + str(a.max())

print "minimum element in a: " + str(a.min())

print "maximum element in each row of a: " + str(a.max(axis=1))

print "minimum element in each row of a: " + str(a.min(axis=1))

print "sum element in each row of a: " + str(a.sum(axis=1))

a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
sum of all elements in a: 190
maximum element in a: 19
minimum element in a: 0
maximum element in each row of a: [ 4  9 14 19]
minimum element in each row of a: [ 0  5 10 15]
sum element in each row of a: [10 35 60 85]


In [64]:
'''
矩阵对象和数组的主要有两点差别：

一是矩阵是二维的，而数组的可以是任意正整数维；

二是矩阵的'*'操作符进行的是矩阵乘法，乘号左侧的矩阵列和乘号右侧的矩阵行要相等，
而在数组中'*'操作符进行的是每一元素的对应相乘，乘号两侧的数组每一维大小需要一致。

数组可以通过asmatrix或者mat转换为矩阵，或者直接生成也可以：

'''
a = np.arange(20).reshape(4, 5)

a = np.asmatrix(a)

print a
print type(a)

b = np.matrix('1.0 2.0; 3.0 4.0')

print b
print type(b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.matrixlib.defmatrix.matrix'>
[[ 1.  2.]
 [ 3.  4.]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [66]:
#数组和矩阵元素的访问可通过下标进行，以下均以二维数组（或矩阵）为例：

a = np.array([[3.2, 1.5], [2.5, 4]])

print a
print a[0][1]


[[ 3.2  1.5]
 [ 2.5  4. ]]
1.5


In [67]:
##通过下标访问来修改数组元素的值

b = a

a[0][1] = 2.0

print "a:"

print a

print "b:"

a:
[[ 3.2  2. ]
 [ 2.5  4. ]]
b:


In [68]:
print b

[[ 3.2  2. ]
 [ 2.5  4. ]]


In [69]:
'''
Python不是真正将a复制一份给b，
而是将b指到了a对应数据的内存地址上。
想要真正的复制一份a给b，可以使用copy

'''

a = np.array([[3.2, 1.5], [2.5, 4]])

b = a.copy()

a[0][1] = 2.0

print "a:"

print a

print "b:"

print b[0][1]

a:
[[ 3.2  2. ]
 [ 2.5  4. ]]
b:
1.5


In [109]:
# 利用':'可以访问到某一维的全部数据，例如取矩阵中的指定列：

a=np.arange(18).reshape(3,6)

print a.shape
print "the 2nd and 4th column of a:"
print a
print a[:,2]
print a[:,[1,3]]
print a[:,[0,2,3]]

print a[0,0:4]
print a[2,:]

print a[0,3:]

print a[1,::2]
print a[1::2,::2]

(3, 6)
the 2nd and 4th column of a:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[ 2  8 14]
[[ 1  3]
 [ 7  9]
 [13 15]]
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]]
[0 1 2 3]
[12 13 14 15 16 17]
[3 4 5]
[ 6  8 10]
[[ 6  8 10]]


In [92]:
#将第一列大于5的元素（6和12）对应的第三列元素（8和14）取出来

b=a[:, 2][a[:, 0] > 5]

print a

print a[:,2]

print a[:, 0]

print a[:, 0]>5

print b

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[ 2  8 14]
[ 0  6 12]
[False  True  True]
[ 8 14]


In [96]:
#使用where函数查找特定值在数组中的位置：

loc = np.where(a==11)

print loc

print loc[0][0]
print loc[1][0]

print a[loc[0][0], loc[1][0]]


(array([1]), array([5]))
1
5
11


In [126]:
#NumPy采用组元(tuple)作为数组的下标

a=np.array([2,3,4,3,3,3]).reshape(2,3)
print a

locs=np.where(a==3)

print type(locs)
print locs


[[2 3 4]
 [3 3 3]]
<type 'tuple'>
(array([0, 1, 1, 1]), array([1, 0, 1, 2]))


In [128]:
#矩阵转置

a = np.random.rand(2,4)

print "a:"

print a

a = np.transpose(a)

print "a is an array, by using transpose(a):"

print a

b = np.random.rand(2,4)

b = np.mat(b)

print "b:"

print b

print np.transpose(b)

a:
[[ 0.17278663  0.25900306  0.89424046  0.92049571]
 [ 0.1799206   0.22455902  0.08449189  0.43825688]]
a is an array, by using transpose(a):
[[ 0.17278663  0.1799206 ]
 [ 0.25900306  0.22455902]
 [ 0.89424046  0.08449189]
 [ 0.92049571  0.43825688]]
b:
[[ 0.16961255  0.95269589  0.24107463  0.37768379]
 [ 0.72657576  0.38020319  0.66187777  0.00818603]]
[[ 0.16961255  0.72657576]
 [ 0.95269589  0.38020319]
 [ 0.24107463  0.66187777]
 [ 0.37768379  0.00818603]]


In [133]:
#矩阵求逆

import numpy.linalg as nlg

a = np.random.rand(2,2)

a = np.mat(a)

print "a:"

print a

ia = nlg.inv(a)

print "inverse of a:"

print ia

print "a * inv(a)"

print a * nlg.inv(a)

a:
[[ 0.57611988  0.76081625]
 [ 0.20378829  0.07775903]]
inverse of a:
[[-0.70531702  6.90102047]
 [ 1.84847149 -5.22572314]]
a * inv(a)
[[  1.00000000e+00   5.58464887e-17]
 [  1.00287991e-16   1.00000000e+00]]


In [135]:
#求特征值和特征向量

a = np.random.rand(3,3)

eig_value, eig_vector = nlg.eig(a)

print a

print "eigen value:"

print eig_value

print "eigen vector:"

print eig_vector

[[ 0.52652589  0.45279729  0.50755203]
 [ 0.94931349  0.76524137  0.21655319]
 [ 0.91410309  0.51169263  0.5146554 ]]
eigen value:
[ 1.74007155 -0.19797815  0.26432926]
eigen vector:
[[-0.48843556 -0.68018386  0.28796602]
 [-0.61349691  0.56549933 -0.78368293]
 [-0.62052578  0.46643373  0.55037863]]


In [136]:
#按列拼接两个向量成一个矩阵：

a = np.array((1,2,3))

b = np.array((2,3,4))

print np.column_stack((a,b))
 


[[1 2]
 [2 3]
 [3 4]]


In [138]:
a = np.random.rand(2,2)

b = np.random.rand(2,2)

print "a:"

print a

print "b:"

print a

c = np.hstack([a,b])

d = np.vstack([a,b])

print "horizontal stacking a and b:"

print c

print d

a:
[[ 0.94923728  0.47602672]
 [ 0.55324291  0.21295194]]
b:
[[ 0.94923728  0.47602672]
 [ 0.55324291  0.21295194]]
horizontal stacking a and b:
[[ 0.94923728  0.47602672  0.43723851  0.95323217]
 [ 0.55324291  0.21295194  0.03692028  0.24293031]]
[[ 0.94923728  0.47602672]
 [ 0.55324291  0.21295194]
 [ 0.43723851  0.95323217]
 [ 0.03692028  0.24293031]]


In [141]:
#缺失值

a = np.random.rand(2,2)

print a

a[0, 1] = np.nan

print np.isnan(a)

print np.nan_to_num(a)

[[ 0.00479932  0.19602893]
 [ 0.28292913  0.16320551]]
[[False  True]
 [False False]]
[[ 0.00479932  0.        ]
 [ 0.28292913  0.16320551]]
